# Generated by Django 4.2.1 on 2023-06-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nc_app', '0002_expert_experience_education_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mentor_images'),
        ),
    ]
