# Generated by Django 4.2.1 on 2023-06-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nc_app', '0005_alter_expert_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='id_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
