# Generated by Django 4.2.1 on 2023-06-09 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nc_app', '0009_rename_expert_detail_mentor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='mentor',
            new_name='expert',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='mentor',
            new_name='expert',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='mentor',
            new_name='expert',
        ),
    ]
