# Generated by Django 4.2.1 on 2023-06-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nc_app', '0010_rename_mentor_detail_expert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='availability',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
