# Generated by Django 4.2.1 on 2023-06-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nc_app', '0013_rename_contact_clientfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientfeedback',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clientfeedback',
            name='business_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clientfeedback',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
