# Generated by Django 4.2.1 on 2023-06-10 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nc_app', '0014_alter_clientfeedback_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=200)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expertises', to='nc_app.expert')),
            ],
        ),
    ]
