# Generated by Django 4.2.1 on 2023-06-10 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nc_app', '0015_expertise'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expertise',
            new_name='Specialization',
        ),
    ]
