# Generated by Django 4.2.1 on 2023-06-14 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nc_app', '0016_rename_expertise_specialization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientfeedback',
            old_name='message',
            new_name='comment',
        ),
    ]
