# Generated by Django 4.2.1 on 2023-06-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nc_app', '0017_rename_message_clientfeedback_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUpForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='clientfeedback',
            name='contact_number',
            field=models.IntegerField(max_length=11),
        ),
        migrations.AlterField(
            model_name='clientfeedback',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
