# Generated by Django 4.2.1 on 2023-06-14 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nc_app', '0018_signupform_alter_clientfeedback_contact_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorBiography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MentorEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MentorExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MentorSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='SignUpForm',
            new_name='SignUp',
        ),
        migrations.RemoveField(
            model_name='education',
            name='expert',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='expert',
        ),
        migrations.RemoveField(
            model_name='specialization',
            name='expert',
        ),
        migrations.RenameModel(
            old_name='Expert',
            new_name='Mentor',
        ),
        migrations.DeleteModel(
            name='Detail',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='Specialization',
        ),
        migrations.AddField(
            model_name='mentorspecialization',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expertises', to='nc_app.mentor'),
        ),
        migrations.AddField(
            model_name='mentorexperience',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='nc_app.mentor'),
        ),
        migrations.AddField(
            model_name='mentoreducation',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='nc_app.mentor'),
        ),
        migrations.AddField(
            model_name='mentorbiography',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='nc_app.mentor'),
        ),
    ]
