# Generated by Django 4.2.1 on 2023-06-14 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nc_app', '0020_msmeaccount_delete_signup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorbiography',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biography', to='nc_app.mentor'),
        ),
    ]
