# Generated by Django 4.2.1 on 2023-06-14 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nc_app', '0021_alter_mentorbiography_mentor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MsmeAccount',
        ),
    ]
